---
- name: Install Package
  hosts: all
  vars:
  - package_name: apache2

  tasks:
  - name: Install the latest version of apache2
    package:
      name: "{{ package_name }}"
      state: latest

  - name: Enable apache2 service
    service:
      name: "{{ package_name }}"
      state: started
      enabled: yes
    tags: packages
